### PR TITLE
Added a C++ Code for Segment tree

### PR DESCRIPTION
**Pull request by shubhamayush12**
A code for segment tree which is a type of data structure which is used to store data about array segments and answer segment queries efficiently while still being flexible enough to allow modifying the array. Time complexity for the code is O(n log n) and space complexity is also O(n log n).

### CODE REVIEW

**Review by Paritosh5876 — APPROVED** [review]

**Comment by Paritosh5876** [comment]
Just write a line about your code and working of your code in description

**Comment by shubhamayush12** [comment]
> Just write a line about your code and working of your code in description

Sir will you please tell me do i need to comment on my code itself?

**Comment by shubhamayush12** [comment]
Sir will I have to create a new pull request?

**Comment by Paritosh5876** [comment]
No ......At the top of this pull request you can see a msg no description added ........just write a line about your code

**Review by Paritosh5876 — APPROVED** [review]

**Comment by shubhamayush12** [comment]
Yes Sir I have added the description

**Pull request merged**
